version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: time_tracker
      POSTGRES_USER: Chelovek051403
      POSTGRES_PASSWORD: Chelovek051403
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    image: time-tracker-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/time_tracker
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
